[package]
name = "token"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.2", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.2", directory = "noir-projects/aztec-nr/uint-note" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.2", directory = "noir-projects/aztec-nr/compressed-string" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.2", directory = "noir-projects/aztec-nr/authwit" }
